---
- name: Install Gerrit required packages
  zypper: name={{ item }} state=present
  with_items:
    - java-1_7_0-openjdk

- name: Create gerrit user
  user: name={{gerrit_user}} state=present

- name: Create gerritr home
  file: path={{gerrit_home}} owner={{gerrit_user}} group=users mode=0764 state=directory

- name: Download gerrit war
  get_url: url={{gerrit_source}} dest={{gerrit_home}}/gerrit.war validate_certs=no use_proxy=yes owner=gerrit group=users
  environment: proxy

- name: Create directory for jQuery
  sudo: yes
  sudo_user: "{{ gerrit_user }}"
  action: file dest={{ gerrit_home }}/etc/ state=directory mode=0755

- name: Create gerrit conf
  sudo: yes
  sudo_user: "{{ gerrit_user }}"
  template: src=gerrit.config dest={{ gerrit_home }}/etc/gerrit.config

- name: Init gerrit
  sudo: yes
  sudo_user: "{{ gerrit_user }}"
  command: chdir={{ gerrit_home }} java -jar gerrit.war init --batch -d "{{ gerrit_home }}"
  environment: proxy

- name: Setup as service
  file: src={{ gerrit_home }}/bin/gerrit.sh dest=/etc/init.d/gerrit state=link

- name: Setup gerrit home in tc
  lineinfile: dest=/etc/default/gerritcodereview
              create=yes
              state=present
              regexp="GERRIT_SITE="
              line="GERRIT_SITE={{gerrit_home}}"
              owner={{gerrit_user}}
              group=users
              mode=0644

- name: Setup as boot service
  service: name=gerrit state=restarted enabled=yes

- name: Create gerrit conf
  sudo: yes
  sudo_user: "{{ gerrit_user }}"
  template: src=gerrit.config dest={{ gerrit_home }}/etc/gerrit.config
  notify:
    - restart gerrit

